# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = [
    { mountPoint = "/"; device = "/dev/mapper/enc-root"; fsType = "ext4"; options = ["noatime"]; }
    { mountPoint = "/boot"; device = "/dev/disk/by-partlabel/EFI\\x20system\\x20partition"; fsType = "vfat"; options = ["noatime" "nofail"]; }
    { mountPoint = "/tmp"; device = "tmpfs"; fsType = "tmpfs"; options = ["nosuid" "nodev" "relatime"]; }
  ] ++ (import ../lib/syncthing.nix { excluding = [ "pdf" ]; });

  boot.initrd.luks.devices.enc-root.device = "/dev/disk/by-label/enc-part";

  swapDevices = [ { device = "/var/swapfile"; size = 4000; } ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  services.xserver.videoDrivers = [ "modesetting" "nvidia" ];

  # hardware.nvidia.prime.sync.enable = true;
  # hardware.nvidia.prime.nvidiaBusId = "PCI:60:0:0";
  # hardware.nvidia.prime.intelBusId = "PCI:0:2:0";

}
