#!/bin/sh

# purpose:
# sh /home/s/code/desktop/dotfiles/generate-zsh-long-conf > ~root/.zshrc; exec zsh

if [ "$(id -u)" = "0" ]; then
    USER="$SUDO_USER"
fi

HOME="$(getent passwd "$USER" | cut -d: -f6)"

grep -Ev '^\. ./\.config/zsh/' < $HOME/.zshrc
grep -Eo '~/\.config/zsh/\w+' < $HOME/.zshrc | xargs -L1 sh -c \
    'f="${1/#\~/'$HOME'}"; cat "$f"' sh
