# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

with config.literals;
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    enc-vg = {
      device = "/dev/disk/by-uuid/a4ee2444-0bc4-4d6c-9754-c7f2353cca35"; preLVM = true; allowDiscards = true;
      inherit keyFile keyFileOffset keyFileSize; fallbackToPassword = true;
    }; # /dev/sda3
    enc-home = {
      device = "/dev/disk/by-uuid/79e9c6d6-6c41-4951-95c2-a98dafe11507"; preLVM = true; allowDiscards = true;
      inherit keyFile keyFileOffset keyFileSize; fallbackToPassword = true;
    }; # /dev/sda4
  };

  fileSystems = pkgs.lib.recursiveUpdate {
    "/" = { device = "/dev/vg/root"; fsType = "ext4"; options = ["noatime"]; };
    "/boot" = { device = "/dev/sda2"; fsType = "vfat"; options = ["noatime" "nofail"]; };
    "/home" = { device = "/dev/mapper/enc-home"; fsType = "ext4"; options = ["noatime" "nofail"]; };
    "/tmp" = { device = "tmpfs"; fsType = "tmpfs"; options = ["nosuid" "nodev" "relatime"]; };
  } (import ../modules/syncthing.nix { inherit (pkgs.lib) recursiveUpdate; });

  swapDevices = [ { device = "/var/swapfile"; size = 4000; } ];

  nix.maxJobs = lib.mkDefault 4;
  hardware.cpu.intel.updateMicrocode = true;
  powerManagement.cpuFreqGovernor = "powersave";
}
