# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # boot.initrd.kernelModules = [ ];
  # boot.kernelModules = [ "kvm-intel" ];
  # boot.extraModulePackages = [ ];

  boot.initrd.luks.devices.enc-root.device = "/dev/disk/by-label/enc-part";

  fileSystems = pkgs.lib.recursiveUpdate {
    "/" = { device = "/dev/mapper/enc-root"; fsType = "ext4"; options = ["noatime"]; };
    "/boot" = { device = "/dev/disk/by-partlabel/EFI\\x20system\\x20partition"; fsType = "vfat"; options = ["noatime" "nofail"]; };
    "/tmp" = { device = "tmpfs"; fsType = "tmpfs"; options = ["nosuid" "nodev" "relatime"]; };
  } (import ../modules/syncthing.nix { inherit (pkgs.lib) recursiveUpdate; excluding = [ "pdf" ]; });

  swapDevices = [ { device = "/var/swapfile"; size = 4000; } ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  # hardware.cpu.intel.updateMicrocode = true;

  services.xserver.videoDrivers = [ "modesetting" "nvidia" ];

  # hardware.nvidia.prime.sync.enable = true;
  # hardware.nvidia.prime.nvidiaBusId = "PCI:60:0:0";
  # hardware.nvidia.prime.intelBusId = "PCI:0:2:0";
}
