#!/usr/bin/env zsh

# Aliases.
alias '...'='../..'
alias '....'='../../..'
alias '.....'='../../../..'
alias '......'='../../../../..'
alias '.......'='../../../../../..'
alias '........'='../../../../../../..'
# vim macro to make another, longer one: yyp^f'lvypf=llvf/yP

v() {
    if [ $# -eq 0 ] && [ -e .session.vim ]; then
        nvim -S .session.vim
    elif [ $# -eq 0 ] && [ -e Session.vim ]; then
        nvim -S Session.vim
    else
        nvim -p "$@"
    fi
}

#

if [ "$(id -u)" = "0" ]; then
    alias m=mount
    alias um=umount
else
    alias m=mpv
fi

if [ -n "$ZSH_DARWIN" ]; then alias ping=/sbin/ping; fi

if ! [ -n "$ZSH_DARWIN" ] || which ls | grep -q /run/current-system; then
  alias ls='ls --color=auto -hb --group-directories-first'
else
  alias ls='ls -hb'
fi

p() { f="$1"; shift 2> /dev/null; ping -c1 "${f:-google.lv}" "$@"; } # tired of writing this over and over again.
pp() { p "$@" || (sleep 0.66; pp "$@"); }

alias l='ls'
alias mv='mv -i'
alias du='du -h'

alias vim=v
[ -z "$ZSH_DARWIN" ] && alias cal='cal -m'
alias frg='find . | rg'
alias grep='grep --colour'
alias watch='watch -n.5'
alias hexdump='hexdump -C'
alias dc='docker-compose'

alias tmux-alt-shell='tmux bind-key v new-window'

alias g=git
alias gst='git status'
alias ga='git add'
alias gd='git diff'
alias gwd='git diff --word-diff'
alias gk='git checkout'
alias gr='git reset'
alias grem='git remote'
alias grb='git rebase'
alias gls='git ls-files'

alias gc='git commit'
alias gca='git commit -a'
alias gm='git commit -am'
alias gam='git commit --amend'
alias g+='git commit --amend -C HEAD'
alias g-='git revert'

# alias r='bundle exec rails'
# alias rk='bundle exec rake'
# alias rsp='bundle exec rspec'
alias r='rails'
alias rk='rake'
alias rsp='rspec'
alias be='bundle exec'
alias b='bundle'
alias dal='direnv allow'
alias dad='direnv deny'
alias rn='react-native'
