#!/usr/bin/env zsh

if [ "$(id -u)" = "0" ]; then
    alias m=mount
    alias um=umount
else
    alias m=mpv
fi

# Aliases.
alias '...'='../..'
alias '....'='../../..'
alias '.....'='../../../..'
alias '......'='../../../../..'
alias '.......'='../../../../../..'
alias '........'='../../../../../../..'
# vim macro to make another, longer one: yyp^f'lvypf=llvf/yP

v() {
    if [ -e .session.vim ] && [ $# -eq 0 ]; then
        nvim -S .session.vim
    else
        nvim -p "$@"
    fi
}

alias vim=v

alias ls='ls --color=auto -hb'
alias l='ls'
alias p='ping google.lv' # tired of writing this over and over again.
alias p1='ping google.lv -c1'
alias mv='mv -i'

alias cal='cal -m'
alias fack='find . | ack'
alias grep='grep --colour'
alias pwgen='pwgen -n 10'
alias watch='watch -n.5'
alias hexdump='hexdump -C'
alias dc='docker-compose'

alias pS='pacman -S'
alias pSs='pacman -Ss'
alias pS='pacman -S'
alias pSy='pacman -Sy'
alias pSu='pacman -Su'
alias pSyu='pacman -Syu'
alias pSyuw='pacman -Syuw'
alias pQ='pacman -Q'
alias pQi='pacman -Qi'
alias pQl='pacman -Ql'
alias pQo='pacman -Qo'
alias pQs='pacman -Qs'

alias g=git
alias gst='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gk='git checkout'
alias gr='git rebase'

alias tmux-alt-shell='tmux bind-key v new-window'
