#!/usr/bin/env zsh

if [ "$(id -u)" = "0" ]; then
    alias m=mount
    alias um=umount
else
    alias m=mpv
fi

# Aliases.
alias '...'='../..'
alias '....'='../../..'
alias '.....'='../../../..'
alias '......'='../../../../..'
alias '.......'='../../../../../..'
alias '........'='../../../../../../..'
# vim macro to make another, longer one: yyp^f'lvypf=llvf/yP

v() {
    if [ $# -eq 0 ] && [ -e .session.vim ]; then
        nvim -S .session.vim
    elif [ $# -eq 0 ] && [ -e Session.vim ]; then
        nvim -S Session.vim
    else
        nvim -p "$@"
    fi
}

alias p='ping google.lv -c1' # tired of writing this over and over again.
pp() { p || (sleep 0.66; pp); }

alias ls='ls --color=auto -hb --group-directories-first'
alias l='ls'
alias mv='mv -i'

alias vim=v
alias cal='cal -m'
alias frg='find . | rg'
alias grep='grep --colour'
alias pwgen='pwgen -n 10'
alias watch='watch -n.5'
alias hexdump='hexdump -C'
alias dc='docker-compose'

alias g=git
alias gst='git status'
alias ga='git add'
alias gc='git commit'
alias gd='git diff'
alias gk='git checkout'
alias gr='git reset'
alias grem='git remote'
alias grb='git rebase'
alias gls='git ls-files'

alias r='bundle exec rails'
alias rk='bundle exec rake'
alias be='bundle exec'
alias b='bundle'
alias dal='direnv allow'
alias zr='exec zsh'

alias tmux-alt-shell='tmux bind-key v new-window'
