#!/usr/bin/env zsh

precmd-color() {
    local -a colors
    (cat ~/.config/zsh/colors 2> /dev/null; echo '0 white white white' ) |
        grep -Em1 "^($(id -u)|$USER|$(hostname)|fallback) " | sed 's/^[^ ]* //'
}
precmdcolorcache="$(precmd-color)"
precmd-color() { echo "${precmdcolorcache}" }

precmd-realm() {
    local merightnow realm depth
    merightnow="$(pwd | sed "s:$HOME::")"
    realm="$(echo $merightnow | grep -Eo '^/[^/]+($|/[^/]+)' | cut -b2-)"
    depth="$(tr -cd '/' <<< "$merightnow" | wc -c)"

    if (( $depth < 2 )); then
        realm="%."
    elif (( $depth == 3 )); then
        realm="$realm/%."
    elif (( $depth > 3 )); then
        realm="$realm %."
    fi

    echo "$realm"
}

# PS1
precmd() {
    __ps1_succ="$?"

    local fst snd thd git ruby succ

    git="$(git branch 2> /dev/null | grep '^*' | tr -cd "a-zA-Z0-9\\-/.")"
    # git="$(git symbolic-ref -q --short HEAD | tr -cd "a-zA-Z0-9\\-/.")"
    ruby="$(rbenv version 2> /dev/null | grep -Po '^\d\S+')"

    [ "$(id -u)" = "0" ] && sep=')' || sep='|'
    read fst snd thd <<< "$(precmd-color)"
    fst="${fst:-105}"; snd="${snd:-105}"; thd="${thd:-105}"
    PS1="%F{$thd}%n$sep%F{$fst}%B$(precmd-realm)%b%F{default} "

    if [ -n "$git" ] && [ -z "$PS1_OMMIT_BRANCH" ]; then
        PS1="$PS1%F{$snd}$git "
    fi

    if [ -n "$ruby" ] && false; then
        PS1="$PS1$ruby "
    fi

    # if git show HEAD:"config/application.rb" &> /dev/null && ! cat notes/db-path 2> /dev/null | xargs -r rails-is-migrated 2> /dev/null; then
    #     PS1="$PS1%F{red}UNMIGRATED "
    # fi

    if [ "$__ps1_succ" = "0" ]; then
        succ="default"
    else
        succ="red"
    fi

    PS1="$PS1%F{$succ}%#%F{default} "
    RPS1=""
}
