#!/usr/bin/env zsh

precmd-color() {
    local -a colors
    (cat ~/.config/zsh/colors 2> /dev/null; echo '0 white white white' ) |
        grep -Em1 "^($(id -u)|$USER|$(hostname)|fallback) " | sed 's/^[^ ]* //'
}
precmdcolorcache="$(precmd-color)"
precmd-color() { echo "${precmdcolorcache}" }

precmd-realm() {
    ruby -e "a, b, *r, l = ENV['PWD'].sub(ENV['HOME'], '').sub(%r{^/}, '').split(?/); puts([a || '%.', b, l].compact.zip(['/', r.any? ? ' ' : '/', '.']).flatten.join[0..-2])"
}

if [ -z "$ZSH_NESTED" ]; then
    export ZSH_NESTED=$$
fi

# PS1
precmd() {
    __ps1_succ="$?"

    local fst snd thd git ruby succ

    git="$(git branch 2> /dev/null | grep '^*' | tr -cd "a-zA-Z0-9\\-_/.")"
    # git="$(git symbolic-ref -q --short HEAD | tr -cd "a-zA-Z0-9\\-/.")"
    ruby="$(rbenv version 2> /dev/null | grep -Eo '^[0-9]\S+')"

    [ "$(id -u)" = "0" ] && sep=')' || sep='|'
    read fst snd thd <<< "$(precmd-color)"
    fst="${fst:-105}"; snd="${snd:-105}"; thd="${thd:-105}"
    PS1="%F{$thd}%n$sep%F{$fst}%B$(precmd-realm)%b%F{default} "

    if [ -n "$git" ] && [ -z "$PS1_OMMIT_BRANCH" ]; then
        PS1="$PS1%F{$snd}$git "
    fi

    if [ -n "$ruby" ] && false; then
        PS1="$PS1$ruby "
    fi

    # if git show HEAD:"config/application.rb" &> /dev/null && ! cat notes/db-path 2> /dev/null | xargs -r rails-is-migrated 2> /dev/null; then
    #     PS1="$PS1%F{red}UNMIGRATED "
    # fi

    if [ "$__ps1_succ" = "0" ]; then
        if [ "$ZSH_NESTED" = "$(ps -p $$ -o ppid=)" ]; then
            succ="green"
        else
            succ="default"
        fi
    else
        succ="red"
    fi

    PS1="$PS1%F{$succ}%#%F{default} "
    RPS1=""
}
