#!/bin/bash

hc() {
    herbstclient "$@"
}
hc keybind Mod4-u           split vertical 0.5

hc emit_hook reload
hc keyunbind --all
hc set_layout max

# settings
hc set frame_gap                 0
hc set window_gap                0
hc set frame_padding             0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings  0
hc set mouse_recenter_gap        0
hc set default_frame_layout      2

# colors
#hc set frame_border_active_color '#ffffff'
#hc set frame_border_normal_color '#101010'
#hc set frame_bg_normal_color '#565656'
#hc set frame_bg_active_color '#345F0C'
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#cccccc'
hc set frame_border_width 0
hc set window_border_width 1
hc set always_show_frame 0
hc set frame_bg_transparent 1

# Object tree ascii art style; can be queried with `hc stack'.
hc set tree_style '╾│ ├└╼─┐'

# General.
hc keybind Mod4-Control-Shift-q quit
hc keybind Mod4-Control-Shift-r reload
hc keybind Mod4-c close_or_remove
hc pad 0   17 0 0 0
#hc pad 0   17 0 26 0

# Tag accessors.
# hc rename default 1
# for tag in "q 1" "w 2" "e 3" "r 4" "a 5" "s 6" "d 7" "f 8"; do
#     read key index <<< $tag
#     hc add     $index
#     hc keybind Mod4-$key       use  $index
#     hc keybind Mod4-Shift-$key move $index
# done
for tag in {e,r,d,f}{q,w,a,s}; do
    hc add $tag
done
hc use eq
hc merge_tag default eq

for tag in {q,w,a,s,e,d}; do
    hc add $tag
done
hc use q
hc merge_tag default q

# cycle through tags
hc keybind Mod4-period  use_index +1 --skip-visible
hc keybind Mod4-comma   use_index -1 --skip-visible
hc keybind Mod4-m       cycle_layout +1
hc keybind Mod4-Shift-m cycle_layout -1

# layouting keys
hc keybind Mod4-semicolon   remove
#hc keybind Mod4-Tab         use_previous
hc keybind Mod4-u           split vertical 0.5
hc keybind Mod4-i           split horizontal 0.5
hc keybind Mod4-g           floating toggle
hc keybind Mod4-o           fullscreen toggle
hc keybind Mod4-t           pseudotile toggle

# resizing
hc keybind Mod4-Control-h resize left   +0.05
hc keybind Mod4-Control-j resize down   +0.05
hc keybind Mod4-Control-k resize up     +0.05
hc keybind Mod4-Control-l resize right  +0.05

# focus
hc keybind Mod4-h focus left
hc keybind Mod4-j focus down
hc keybind Mod4-k focus up
hc keybind Mod4-l focus right

# switching
hc keybind Mod4-Shift-h shift left
hc keybind Mod4-Shift-j shift down
hc keybind Mod4-Shift-k shift up
hc keybind Mod4-Shift-l shift right

# mouse
hc mouseunbind --all
hc mousebind Mod4-Button1 move
hc mousebind Mod4-Button2 resize
hc mousebind Mod4-Button3 zoom

# focus
hc keybind Mod4-n       cycle     +1 # Cycles through frame shit.
hc keybind Mod4-Shift-n cycle_all +1 # Cycles through window shit.
hc keybind Mod4-Shift-p cycle_all -1
hc keybind Mod4-p       cycle     -1

# rules
hc unrule --all
hc rule focus=on
hc rule class~'Chromium' ewmhnotify=off ewmhrequests=off
hc rule class~'Skype' tag=14

# meskarune's rules
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class~'[Ww]bar' manage=off

#hc rule class=XTerm tag=3 # move all xterms to tag 3
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
#hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
#hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
