#!/usr/bin/env zsh

# these don't seem to be change anything :(
# defaults write -g InitialKeyRepeat -int 10 # normal minimum is 15 (225 ms)
# defaults write -g KeyRepeat        -int 1 # normal minimum is 2 (30 ms)

xset r rate 175 25

cd "$(dirname "$0")"

# caps = super button

setxkbmap "xkbmap-custom,ru" -print -option grp:rctrl_rshift_toggle -option caps:none > xkbmap.out
xkbcomp -I"$(dirname "$(pwd)")" xkbmap.out $DISPLAY &> /dev/null

xmodmap -e 'keycode 66 = Super_L'
