#!/bin/sh

# purpose:
# ./generate-zsh-long-conf | sudo tee ~root/.zshrc > /dev/null

if [ "$(id -u)" = "0" ]; then
    USER="$SUDO_USER"
fi

HOME="$(getent passwd "$USER" | cut -d: -f6)"

grep -Ev '^\. ./\.config/zsh/' < $HOME/.zshrc
grep -Eo '~/\.config/zsh/[^#]+' < $HOME/.zshrc | xargs -r -L1 sh -c \
    'f="${1/#\~/'$HOME'}"; cat "$f"' sh
