#!/usr/bin/env zsh

# n * 15 = ms
# defaults write -g InitialKeyRepeat -int 9
# defaults write -g KeyRepeat -int 2

xset r rate 140 23 # ms delay + repeats per sec

cd "$(dirname "$0")"

# caps = super button

setxkbmap "xkbmap-custom,ru" -print -option grp:rctrl_rshift_toggle -option caps:none > xkbmap.out
xkbcomp -I"$(dirname "$(pwd)")" xkbmap.out $DISPLAY &> /dev/null

xmodmap -e 'keycode 66 = Super_L'
